export type Difficulty = 'einfach' | 'mittel' | 'schwer';
export type SRSStatus = 'neu' | 'lernend' | 'wiederholen' | 'beherrscht';

export interface CardImage {
  type: 'base64' | 'url';
  data: string; // base64 string or URL
  mimeType?: string;
}

export interface CardSet {
  id: string;
  userId: string;
  name: string;
  description?: string;
  subject?: string;
  examiner?: string;
  color: string;
  createdAt: string;
  updatedAt: string;
}

export const SET_COLORS = [
  '#6366f1', '#8b5cf6', '#ec4899', '#ef4444',
  '#f59e0b', '#22c55e', '#14b8a6', '#3b82f6',
  '#f97316', '#a855f7', '#06b6d4', '#84cc16',
];

export interface Flashcard {
  id: string;
  front: string;
  frontImage?: CardImage;
  back: string;
  backImage?: CardImage;
  subjects: string[];
  examiners: string[];
  difficulty: Difficulty;
  customTags: string[];
  setId?: string;
  flagged?: boolean;
  // "Parkiert" — explicitly excluded from all study pickers (daily plan,
  // Lernen, Prüfungsmodus, MC-Session). Card stays in Library with a
  // visual badge so the user can manage it; they can unparken anytime.
  // Different from `flagged` (which means "had trouble with it lately")
  // and different from priority C (which still shows up if you pick C).
  blacklisted?: boolean;
  // Priority for exam-prep focus mode.
  //   'A' = must know (must master before exam)
  //   'B' = should know
  //   'C' = nice to know
  //   undefined = not yet classified — treated as B for default filtering
  // Set either automatically via classifyPriority() heuristic or manually
  // by the user via the inline picker on card front.
  priority?: 'A' | 'B' | 'C';
  // Persistent MC questions for the MC-Lernmodus. Generated by AI once,
  // then cached forever (or until user regenerates manually). Adaptive
  // count: 3 for short cards, 5-7 for complex ones.
  // The format mirrors MCHintResult from src/utils/geminiMCHint.ts so we
  // can reuse the existing rendering widget.
  mcQuestions?: Array<{
    question: string;
    type: 'single' | 'multiple';
    options: Array<{ id: string; text: string; correct: boolean }>;
    explanation: string;
    topic: string;
  }>;
  mcQuestionsGeneratedAt?: string; // ISO timestamp — used to detect stale MC after card edits
  // Exam frequency / probability (set via JSON import)
  timesAsked?: number;
  askedByExaminers?: string[];
  askedInCatalogs?: string[];
  probabilityPercent?: number;
  createdAt: string; // ISO date string
  updatedAt: string; // ISO date string
  // SM-2 SRS fields
  interval: number;       // days until next review
  repetitions: number;    // number of successful reviews
  easeFactor: number;     // multiplier (default 2.5)
  nextReviewDate: string; // ISO date string
  // Set ONCE the first time a card crosses rep=0 → rep≥1 (i.e. the first
  // successful rating). Never updated after that, never touched by edits or
  // merges. This is the authoritative "when did this card stop being new?"
  // signal — used by the Dashboard reconciler so the "Neu heute" count is
  // independent of the snapshot's reliability.
  firstStudiedAt?: string;
}

export interface AppSettings {
  subjects: string[];
  examiners: string[];
  customTags: string[];
  studyStreak: number;
  lastStudiedDate: string | null;
  // Exam countdown & daily goal
  examDate?: string;        // ISO date string (YYYY-MM-DD)
  dailyNewCardGoal: number;   // default: 10
  // 'manual' = use dailyNewCardGoal as-is
  // 'auto'   = derive from unseen-in-focus / (daysUntilExam × 0.5), with
  //            the manual value as upper cap so the user retains control
  dailyNewCardGoalMode?: 'manual' | 'auto';
  dailyReviewCap: number;     // max reviews shown per day (default: 9999 = no cap)
  // Daily progress snapshot (resets each day)
  dailyPlanSnapshot?: {
    date: string;           // toDateString() key
    totalCards: number;     // size of plan when session was first started today
    newCardsDone: number;   // new cards already introduced today (persists across session breaks)
    totalDone: number;      // all cards rated ≥1 (Schwer/Gut/Einfach) today — for progress display
  };
  autoUnflagEnabled: boolean;        // remove flag after 2 correct days in Prüfungsmodus
  autoUnflagNotification?: {
    date: string;      // toDateString() key
    count: number;
    dismissed: boolean;
  };
  anthropicApiKey?: string;           // stored client-side for AI merge feature
  geminiApiKey?: string;              // stored client-side for AI card revision (Google AI Studio)
  groqApiKey?: string;               // stored client-side for Groq fallback (free, no credit card)
  studyOrder?: 'new-first' | 'review-first' | 'mixed'; // stored client-side
  // Focus-Modus: when set to 'A' or 'AB', the Dashboard + "Jetzt lernen" only
  // consider cards with that priority. Everything else (lower-priority cards)
  // is invisible until the user widens focus. The motivation engine: with
  // 1037 cards and 60 days to exam, retaining everything is impossible —
  // focusing on 200 must-know cards is realistic and gives a "done today"
  // feeling that the global view can't.
  focusMode?: 'all' | 'A' | 'AB';
}

export interface FlagAttempt {
  id: string;
  cardId: string;
  answeredCorrectly: boolean;
  attemptedAt: string; // YYYY-MM-DD calendar date
  createdAt: string;
}

export interface CardLink {
  id: string;
  cardId: string;
  linkedCardId: string;
  linkType: 'child' | 'related';
  createdAt: string;
}

export type RatingValue = 0 | 1 | 2 | 3; // Nochmal | Schwer | Gut | Einfach

export interface StudyRating {
  label: string;
  value: RatingValue;
  color: string;
  bgColor: string;
  hoverColor: string;
}

export const STUDY_RATINGS: StudyRating[] = [
  { label: 'Nochmal', value: 0, color: '#ef4444', bgColor: 'bg-red-500/10', hoverColor: 'hover:bg-red-500/20' },
  { label: 'Schwer',  value: 1, color: '#f59e0b', bgColor: 'bg-amber-500/10', hoverColor: 'hover:bg-amber-500/20' },
  { label: 'Gut',     value: 2, color: '#22c55e', bgColor: 'bg-green-500/10', hoverColor: 'hover:bg-green-500/20' },
  { label: 'Einfach', value: 3, color: '#3b82f6', bgColor: 'bg-blue-500/10', hoverColor: 'hover:bg-blue-500/20' },
];

export const DEFAULT_SUBJECTS = [
  'BWL', 'Personalmanagement', 'Unternehmensorganisation', 'Wirtschaftsrecht',
  'Marketing', 'Finanzmanagement', 'Steuerrecht', 'Kostenrechnung', 'VWL',
  'Rechnungswesen', 'Moderne Geschäftskonzepte', 'verantwortungsvolle Unternehmensführung',
  'Wirtschaftspolitik', 'Logistik', 'Projektmanagement', 'Wissenschaftliches Arbeiten',
  'Keine Ahnung', 'E-Commerce', 'Arbeitsrecht',
];

export const DEFAULT_EXAMINERS = [
  'Agnieszka Zablocki',
  'Andreas Miksche',
  'Andreas Raschke',
  'Andreas Tschiltsch',
  'Bettina Gneisz-Al-Ani',
  'Birgit Schaller',
  'Christoph Bolzer',
  'Christine Güttel',
  'Elisabeth Rührig',
  'Florian Schallmeiner',
  'Georg Behm',
  'Gerald Hollaus',
  'Hermann Frank',
  'Katharina Rotter',
  'Katharina Ulm',
  'Kessler / Keßler',
  'Livia Rainsberger',
  'Maija Worek',
  'Manfred Schieber',
  'Margit Winter',
  'Martin Paier',
  'Melanie Rypar',
  'Michael Bauer',
  'Patrick Batka',
  'Philipp Jaklin',
  'Regina Rastbichler',
  'Roman Nedwed',
  'Ronald Schuster',
  'Stefan Wrbka',
  'Zöbl Martina',
];

export const getSRSStatus = (card: Flashcard): SRSStatus => {
  if (card.repetitions === 0) return 'neu';
  if (card.interval <= 1) return 'lernend';
  if (card.interval <= 21) return 'wiederholen';
  return 'beherrscht';
};

export const isDueToday = (card: Flashcard): boolean => {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const reviewDate = new Date(card.nextReviewDate);
  reviewDate.setHours(0, 0, 0, 0);
  return reviewDate <= today;
};
